version: '3'

services:
  flutter-demo-app:
    build: .                 # Build từ Dockerfile ở thư mục hiện tại
    container_name: ubuntu_sandbox
    restart: always
    ports:
      - "8080:8080"          # Map cổng 8080 của máy chủ vào 8080 của container
    volumes:
      - ./data:/app/data
